FROM {{ namespace }}/{{ image_prefix }}designate-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block designate_sink_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_distro in ['fedora', 'centos', 'oraclelinux', 'rhel'] %}
       {% if base_distro_tag in ['28', '8'] %}
       {% set designate_sink_packages = [
            'openstack-designate-sink',
            'python3-designateclient'
        ] %}
       {% else %}
       {% set designate_sink_packages = [
            'openstack-designate-sink',
            'python-designateclient'
        ] %}
       {% endif %}
    {% elif base_distro in ['debian', 'ubuntu'] %}
       {% set designate_sink_packages = [
            'designate-sink',
            'python-designateclient'
        ] %}
    {% endif %}
{{ macros.install_packages(designate_sink_packages | customizable("packages")) }}
{% endif %}

{% block designate_sink_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER designate
