FROM {{ namespace }}/{{ image_prefix }}neutron-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block ironic_neutron_agent_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}

    {% if base_distro in ['fedora', 'centos', 'oraclelinux', 'rhel'] %}
        {% if base_distro_tag in ['28', '8'] %}
        {% set ironic_neutron_agent_packages = [
            'python3-networking-baremetal',
            'python3-ironic-neutron-agent'
        ] %}
        {% else %}
        {% set ironic_neutron_agent_packages = [
            'python-networking-baremetal',
            'python-ironic-neutron-agent'
        ] %}
        {% endif %}
    {% elif base_distro in ['debian', 'ubuntu'] %}

RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
            && /bin/false

    {% endif %}

{{ macros.install_packages(ironic_neutron_agent_packages | customizable("packages")) }}

{% endif %}


{% block ironic_neutron_agent_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER neutron
