FROM {{ namespace }}/{{ image_prefix }}openstack-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block collectd_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{{ macros.configure_user(name='collectd') }}

{% set collectd_packages = [
    'collectd'
] %}

{% if base_distro in ['fedora', 'centos', 'oraclelinux', 'rhel'] %}
  {% if base_distro_tag in ['28','8'] %}
{# NOTE(aschultz): missing packages?
INFO:kolla.common.utils.collectd:No match for argument: collectd-amqp1
INFO:kolla.common.utils.collectd:No match for argument: collectd-procevent
INFO:kolla.common.utils.collectd:No match for argument: collectd-sysevent
INFO:kolla.common.utils.collectd:No match for argument: python-collectd-gnocchi
#}
  {% set collectd_packages = collectd_packages + [
      'collectd-amqp',
      'collectd-apache',
      'collectd-bind',
      'collectd-ceph',
      'collectd-chrony',
      'collectd-curl',
      'collectd-curl_json',
      'collectd-curl_xml',
      'collectd-dbi',
      'collectd-disk',
      'collectd-dns',
      'collectd-generic-jmx',
      'collectd-ipmi',
      'collectd-log_logstash',
      'collectd-mcelog',
      'collectd-memcachec',
      'collectd-mysql',
      'collectd-netlink',
      'collectd-openldap',
      'collectd-ovs_events',
      'collectd-ovs_stats',
      'collectd-ping',
      'collectd-python',
      'collectd-sensors',
      'collectd-smart',
      'collectd-snmp',
      'collectd-snmp_agent',
      'collectd-utils',
      'collectd-virt',
      'collectd-write_http',
      'collectd-write_kafka',
      'collectd-write_prometheus'
  ] %}
  {% else %}
  {% set collectd_packages = collectd_packages + [
      'collectd-amqp1',
      'collectd-apache',
      'collectd-bind',
      'collectd-ceph',
      'collectd-chrony',
      'collectd-connectivity',
      'collectd-curl',
      'collectd-curl_json',
      'collectd-curl_xml',
      'collectd-dbi',
      'collectd-disk',
      'collectd-dns',
      'collectd-generic-jmx',
      'collectd-ipmi',
      'collectd-log_logstash',
      'collectd-mcelog',
      'collectd-memcachec',
      'collectd-mysql',
      'collectd-netlink',
      'collectd-openldap',
      'collectd-ovs-events',
      'collectd-ovs-stats',
      'collectd-ping',
      'collectd-procevent',
      'collectd-python',
      'collectd-sensors',
      'collectd-smart',
      'collectd-snmp',
      'collectd-snmp-agent',
      'collectd-sysevent',
      'collectd-utils',
      'collectd-virt',
      'collectd-write_http',
      'collectd-write_kafka',
      'collectd-write_prometheus',
      'python-collectd-gnocchi'
  ] %}
  {% endif %}

  {% if base_arch in ['x86_64', 'ppc64le'] %}
      {% set collectd_packages = collectd_packages + [
        'collectd-iptables'
        ] %}
  {% endif %}

  {% if base_arch =='x86_64' %}
{# NOTE(aschultz): missing packages?
INFO:kolla.common.utils.collectd:No match for argument: collectd-rdt
INFO:kolla.common.utils.collectd:No match for argument: collectd-turbostat
#}
    {% if base_distro_tag in ['28', '8'] %}
      {% set collectd_packages = collectd_packages + [
        'collectd-hugepages',
      ] %}
    {% else %}
      {% set collectd_packages = collectd_packages + [
        'collectd-hugepages',
        'collectd-rdt',
        'collectd-turbostat'
      ] %}
    {% endif %}

  {% endif %}
  {% if base_distro not in ['fedora'] %}
# make sure, collectd is pulled from centos-opstools
RUN yum-config-manager --disable epel
  {% endif %}
{% endif %}

{{ macros.install_packages(collectd_packages | customizable("packages")) }}

COPY extend_start.sh /usr/local/bin/kolla_extend_start
RUN chmod 755 /usr/local/bin/kolla_extend_start \
    && chown -R collectd /var/lib/collectd \
    && chown -R collectd /etc/collectd* \
    && chown -R collectd /var/run/

{% block collectd_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER collectd
