FROM {{ namespace }}/{{ image_prefix }}heat-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block heat_engine_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_distro in ['fedora', 'centos', 'oraclelinux', 'rhel'] %}
        {% set heat_engine_packages = [
            'openstack-heat-engine'
        ] %}
        {% if base_distro_tag in ['28', '8'] %}
        {% set heat_engine_packages = heat_engine_packages + [
            'python3-barbicanclient',
            'python3-zaqarclient'
        ] %}
        {% else %}
       {% set heat_engine_packages = heat_engine_packages + [
            'python-barbicanclient',
            'python-zaqarclient'
        ] %}
        {% endif %}
    {% elif base_distro in ['debian', 'ubuntu'] %}
        {% set heat_engine_packages = ['heat-engine'] %}
    {% endif %}
{{ macros.install_packages(heat_engine_packages | customizable("packages")) }}

{% endif %}
{% block heat_engine_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER heat
