FROM {{ namespace }}/{{ image_prefix }}vitrage-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block vitrage_api_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}

    {% if base_distro in ['fedora', 'centos', 'oraclelinux', 'rhel'] %}
        {% if base_distro_tag in ['28', '8'] %}

        {% set vitrage_api_packages = [
            'httpd',
            'mod_wsgi',
            'mod_ssl',
            'python3-ldappool',
            'openstack-vitrage-api'
        ] %}

        {% else %}

        {% set vitrage_api_packages = [
            'httpd',
            'mod_wsgi',
            'mod_ssl',
            'python2-ldappool',
            'openstack-vitrage-api'
        ] %}

        {% endif %}

{{ macros.install_packages(vitrage_api_packages | customizable("packages")) }}
RUN sed -i -r 's,^(Listen 80),#\1,' /etc/httpd/conf/httpd.conf \
    && sed -i -r 's,^(Listen 443),#\1,' /etc/httpd/conf.d/ssl.conf

    {% elif base_distro in ['debian', 'ubuntu'] %}

RUN echo '{{ install_type }} not yet available for {{ base_distro }}' \
    && /bin/false

    {% endif %}

{% endif %}


COPY extend_start.sh /usr/local/bin/kolla_vitrage_extend_start
RUN chmod 755 /usr/local/bin/kolla_vitrage_extend_start

{% block vitrage_api_footer %}{% endblock %}
{% block footer %}{% endblock %}
